### ISSUE TITLE
Background is black when using guibg=NONE

### ISSUE THREAD

**Issue by TheSmallTeaBoi** [folke/twilight.nvim#15]
This is how it looks without `guibg=NONE`:
![image](https://user-images.githubusercontent.com/69133598/129967560-aeeebb67-4a13-436c-a89e-d580b4ab3b98.png)
and here's how it looks with it:
![image](https://user-images.githubusercontent.com/69133598/129967705-a8c8b386-5fff-4a6b-adc3-b6822da93e4b.png)

(I use this option to set vim's bg to my terminal's, in case there's a better way of doing this)

**Comment by axieax** [comment]
Having the same issue here. Is there a way to ignore background colour and only adjust/dim treesitter syntax highlighting?

**Comment by matdexir** [comment]
Hi Guys, I found a little workaround/hack that only requires 4 lines of lua code. 

```lua
local ok, hl = pcall(vim.api.nvim_get_hl_by_name, "Normal", true)
 if hl["background"] == nil then
   bg = "NONE"
end
```
The issue lies with `config.lua` where the background defaults to `#000000` whenever the highlighting for the background is set to NONE.
So, if you want it to work properly you have to ensure that  `guibg=NONE`.
If you want to use my hack:
- Find where the twilight source code is on your machine.
- Add the snippet of code I wrote to twilight.nvim/lua/twilight/config.lua

![2021-09-03-07-50-15_1920x1080](https://user-images.githubusercontent.com/58453130/131931137-6fc01fdf-93d6-4eda-977c-037a8e362cff.png)

VOILA! 

![2021-09-03-08-10-14_1920x1080](https://user-images.githubusercontent.com/58453130/131931413-6469ef58-13e4-4253-a000-2649fc9ee89b.png)

Note that this is only a hack(which may result in bugs) and hopefully the maintainer finds a proper way of solving this issue.

**Comment by axieax** [comment]
Hello @folke sorry for the bump, but could we get some updates on this on the repo (potentially a merge request/commit that resolves this)?

**Comment by evantravers** [comment]
I just started seeing this… I think my colorscheme adjusted the way it calculates background.

**Comment by loqusion** [comment]
[benstockil/twilight.nvim](https://github.com/benstockil/twilight.nvim) fixes the issue for me. Personally, I'm using it until it's fixed in the main repo.
