### ISSUE TITLE
Lagging a lot while moving horizontally 

### ISSUE THREAD

**Issue by LamprosPitsillos** [folke/twilight.nvim#26]
https://user-images.githubusercontent.com/61395246/165488304-d487b8e6-a9f8-4efe-a9f0-4c5c888e34e9.mp4

It lags a lot after a few seconds of Twilight being ON.

**Comment by snowmang1** [comment]
Same thing is happening to me, the memory usage is skyrocketing according to activity manager (on MacOS). I thought the problem was with tree-sitter but I turned that off and the same thing is still happening. If someone explains to me how to get a log output, Id be happy to put one here.

I also tried messing with the amount of lines highlighted and that does not seem to change results (I tried 1, 5, and 10 highlighted lines).
